---
title: 'knitr example: maps and shiny'
author: "Jenna Krall"
date: "October 29, 2014"
output: 
    html_document:
        number_sections: yes
        toc: yes 
runtime: shiny
---



```{r, echo=FALSE, message=F, warning=F}
library(knitr)
opts_chunk$set(echo=F, message=F, warning=F)
```

# Required packages

Required packages from CRAN: 

1. googleVis
2. shiny

```{r packages}
suppressPackageStartupMessages(library(googleVis))
library(shiny)

```


# Embedding maps with googleVis

## Map of Jensen Beach, FL
```{r locbeach, echo = F, results = 'asis', cache = T}

op <- options(gvis.plot.tag='chart')
jensen <- data.frame(matrix(c("Jensen Beach, FL", "Jensen Beach"), nrow = 1))

colnames(jensen) <- c("loc", "tip")
map1 <- gvisMap(jensen, "loc", "tip", options = list(zoomLevel = 5,
                height = 200, width = 200))
plot(map1)

```



## Map of Emory University
```{r emory, echo = F, results = 'asis', cache = T}


emory <- data.frame(matrix(c("1518 Clifton Road northeast, Atlanta, GA", 
                             "1518 Clifton Road northeast, Atlanta, GA"), nrow = 1))

colnames(emory) <- c("loc", "tip")
map1 <- gvisMap(emory, "loc", "tip", options = list(zoomLevel = 15,
                height = 200, width = 200))
plot(map1)

```



# Shiny applications in R markdown documents

## Exploring turtle crawl data
<iframe src="https://jkrall.shinyapps.io/turtle-explore" style="border: none; width: 1000px; height: 500px"></iframe>

## Shiny for teaching

```{r teach, echo = FALSE}
library(shiny)
shinyApp(
  
  ui = fluidPage(
       titlePanel("Central limit distribution"),
#       
     sidebarLayout(
         sidebarPanel(
            selectInput("dist", label = h3("Choose distribution"), 
                  choices = list("Normal" = "Normal", 
                  "Bernoulli" = "Bernoulli",
                  "Poisson" = "Poisson"), selected = "Normal"),

      sliderInput("nsamp", "Number of samples in each study",
        min = 1, max = 1000,
        value = 10, animate = TRUE),
     sliderInput("N", "Number of studies",
        min = 1, max = 1000,
        value = 10, animate = TRUE)
      
     ),
   
  mainPanel(
    textOutput("text1"),
    plotOutput("plot1") )
   
   )
),
  
  server = function(input, output) {
    output$text1 <- renderText({paste("Distribution=", input$dist)})
    output$plot1 <- renderPlot({
        
        #get input values
        nsamp <- input$nsamp
        N <- input$N
        
        #generate random numbers
        if(input$dist == "Normal") {
            x <- rnorm(nsamp * N)
        }else if(input$dist == "Bernoulli") {
            x <- rbinom(nsamp * N, size = 1, prob = 0.5)
        }else if(input$dist == "Poisson") {
            x <- rpois(nsamp * N, 5)
        }
        
        #find sample means
        x <- matrix(x, nrow = N)
        x <- rowMeans(x)
        #plot
        hist(x, xlab = "Value of xbar", ylab = "Frequency", main = "")
    })
  },
  
  options = list(height = 500)
)
```

